### PR TITLE
Feature/TR-5072/add sandbox

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

Add a sandbox for easing the development of the engine

### Details

Additional tooling has been added, for building and managing the sandbox.
The sandbox is made using Svelte. It offers a way to interact with the engine using a visual component and it also displays the state.

### How to test

- install the package: `npm ci`
- run the sandbox: `npm run dev`
- play with the opened sandbox...

### CODE REVIEW

**Review by rgomeztao — APPROVED** [review]
awesome tool to play with! :)
* code looks nice
* playing with it in local was fun
* test runs  okey in local

- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by shaveko — CHANGES_REQUESTED** [review]
Tests run well on my environment, sandbox is very cool and looks super nice!!!

I believe this feature is worth to be mentioned in README.md.

**Comment by shaveko** [comment]
I've also noticed the browser opens sandbox before server starts listening on 5550 port

**Review by shaveko — APPROVED** [review]
TOP! 

Now works super nice, no issue found

**Pull request merged**
