### PR TITLE
Fix/TR-5071/Do not trim unary operators when correcting the expression

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

Fix a regression occurring with the corrector mode.
Fix an issue with the instant computation mode.

### Details

Issues fixed:
- The corrector mode was too aggressive as it was trimming all operators, including the unary operators.
- When the instant mode is activated, it was impossible to start a new expression after having evaluated it explicitly without actually clearing the calculator.
- When adding a parenthesis after a value, glue is added automatically for continuing the expression, but this does not trigger instant computation and the expression grows.

Several changes apply:
- the corrector only trims binary operators and keeps unary operators.
- a condition has been added for replacing the expression if it was evaluated and a new value is entered
- the instant mode now applies after the possible glue term has been added, in order to also take care of the possible multiply by.
- the condition for replacing the expression with the term has been moved to a dedicated strategy

### How to test
- run the tests: `npm test`
- run the sandbox: `npm run dev`
- try to evaluate with and without the instant and the corrector modes:
    - `3#`
    - `10+20%`
    - `10+20`, evaluate, then `%`
    - `3+2+4+5`
    - `3+5`, then evaluate, then `9-2`

### CODE REVIEW

**Review by shaveko — APPROVED** [review]
Looks good to me. Tests run well

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by shaveko** [comment]
found an issue:

With instant computattion mode I do `2+2` than `+`, it calultaes the result, but trims `+`, so when I press `6` - it is considered as a new expression and answer is forgotten

**Review by rgomeztao — APPROVED** [review]
more strategies!!! always welcomed

tests runs good on local
image


the expected behaviors listed seems to work on testing
image

nice job!

**Review by shaveko — APPROVED** [review]
Sweet! Didn't manage to break taht solid thing this time.

Awesome job!

**Pull request merged**
